development:
  dialect: postgres
  database: management
  user: tibi
  password: test
  host: 127.0.0.1
  pool: 5

test:
  url: {{envOr "TEST_DATABASE_URL" "postgres://postgres:postgres@127.0.0.1:5432/golang_test?sslmode=disable"}}

production:
  url: {{envOr "DATABASE_URL" "postgres://pzjbplisrrlrdn:1cb88f27c89002468cfc7b3936be4583e569f262fe44161d8ae92c812071bf77@ec2-54-217-204-34.eu-west-1.compute.amazonaws.com:5432/d75sn93f22hu4f?sslmode=require"}}
