development:
  dialect: postgres
  database: website
  user: tibi
  password: PSBBedut5QwrZCWU
  host: 127.0.0.1
  pool: 20

test:
  url: {{envOr "TEST_DATABASE_URL" "postgres://postgres:postgres@127.0.0.1:5432/golang_test?sslmode=disable"}}

production:
  url: {{envOr "DATABASE_URL" "postgres://postgres:postgres@127.0.0.1:5432/golang_production?sslmode=disable"}}
